name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # ubuntu-18.04 is used as it is the latest fully supported base OS
  # right now.
  # See https://github.com/actions/virtual-environments#available-environments
  pr_presubmit:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        container:
        - "python:3.5-buster"
        - "alpine:3.12"
    container:
      image: ${{ matrix.container }}

    steps:
    - uses: actions/checkout@v2
    - name: install Debian dependencies
      if: ${{ matrix.container == 'python:3.5-buster' }}
      run: ./kokoro/rodete/fetch_dependencies.sh
    - name: install Alpine dependencies
      if: ${{ matrix.container == 'alpine:3.12' }}
      run: ./kokoro/alpine/fetch_dependencies.sh
    - name: setup build directory
      run: meson build
    - name: build
      run: ninja -C build
    - name: test
      run: meson test --print-errorlogs -C build
    - name: install
      run: |
        DESTDIR=out meson install -C build
        find build/out/
        test -x build/out/usr/local/bin/glome
        test -x build/out/usr/local/sbin/glome-login
        test -f build/out/usr/local/etc/glome/config
        test -f build/out/usr/local/include/glome.h
        # Dereference the library and check that it points to a valid file.
        test -f build/out/usr/local/lib/libglome.so || \
        test -f build/out/usr/local/lib/x86_64-linux-gnu/libglome.so

  pr_code_format:
    runs-on: ubuntu-18.04
    container:
      # Use Ubuntu 20.04 for a newer clang-format
      image: "ubuntu:20.04"
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: |
        export DEBIAN_FRONTEND=noninteractive
        apt-get update
        apt-get install -y clang-format
    - name: check format
      run: |
        find . -name "*.c" -or -name "*.h" | \
          xargs clang-format --Werror --dry-run --style=google

  python_presubmit:
    runs-on: ubuntu-18.04
    container:
      image: "python:3.6-buster"

    steps:
    - uses: actions/checkout@v2
    - name: install dependencies from PyPI
      run: python -m pip install -r python/requirements.txt
    - name: run yapf test
      run: yapf -d --style google python/pyglome/*.py python/test/*.py
    - name: run pylint test
      run: pylint python/pyglome/*.py
    - name: run unit tests
      run: |
        cd python
        python -m test

  pr_java_test:
    runs-on: ubuntu-18.04
    container:
      image: "maven:3.6.3-jdk-8"
    steps:
    - uses: actions/checkout@v2
    - name: run linter and test java
      run: |
        mvn compile
        mvn test

  golang_presubmit:
    runs-on: ubuntu-18.04
    container:
      image: "golang:1.15.1-buster"
    defaults:
      run:
        working-directory: go
    steps:
    - uses: actions/checkout@v2
    - name: verify format
      run: |
        gofmt -d .
        test "$(gofmt -d .)" = ""
    - name: run golint
      run: |
        go get -u golang.org/x/lint/golint
        golint -set_exit_status=1 ./...
    - name: run unit tests
      run: go test ./...

  shell_presubmit:
    runs-on: ubuntu-18.04
    container:
      image: "koalaman/shellcheck-alpine:v0.7.1"
    steps:
    - uses: actions/checkout@v2
    - name: test POSIX conformance and lint
      run: find . -name "*.sh" | xargs shellcheck --shell=sh
